language: java
jdk: openjdk12

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - echo $GPG_SECRET_KEYS | base64 --decode | gpg2 --import
  - echo $GPG_OWNERTRUST | base64 --decode | gpg2 --import-ownertrust
  - cp .travis.settings.xml $HOME/.m2/settings.xml  
  - mvn -B clean deploy -Prelease

deploy:
  - provider: releases
    api_key: "${GITHUB_TOKEN}"
    file_glob: true
    file: target/*.jar
    skip_cleanup: true
    on:
      repo: "${TRAVIS_REPO_SLUG}"
      branch: master
      tags: true
